// Generated by BUCKLESCRIPT VERSION 3.2.0, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Printf from "bs-platform/lib/es6/printf.js";
import * as Complex from "bs-platform/lib/es6/complex.js";
import * as Reprocessing from "/Users/sansouci/Desktop/fft/node_modules/reprocessing/src/Reprocessing.js";

Curry._1(Printf.printf(/* Format */[
          /* Float */Block.__(8, [
              /* Float_f */0,
              /* No_padding */0,
              /* No_precision */0,
              /* Char_literal */Block.__(12, [
                  /* "\n" */10,
                  /* End_of_format */0
                ])
            ]),
          "%f\n"
        ]), Complex.add(/* record */[
            /* re */1.0,
            /* im */1.0
          ], /* record */[
            /* re */0.1,
            /* im */0.1
          ])[/* re */0]);

Reprocessing.hotreload(/* None */0, "src/index.re");

export {
  
}
/*  Not a pure module */
