// Generated by BUCKLESCRIPT VERSION 3.2.0, PLEASE EDIT WITH CARE


function create(kind, _, size) {
  if (kind) {
    return new Array(size);
  } else {
    return new Float64Array(size);
  }
}

function blit(a1, a2) {
  for(var i = 0 ,i_finish = a1.length; i <= i_finish; ++i){
    a2[i] = a1[i];
  }
  return /* () */0;
}

var Array1 = /* module */[
  /* create */create,
  /* blit */blit
];

var float64 = /* Float64 */0;

var complex64 = /* Complex64 */1;

var c_layout = /* C_layout */0;

export {
  float64 ,
  complex64 ,
  c_layout ,
  Array1 ,
  
}
/* No side effect */
